# Installation of Packages / Libraries

 Numpy
 Pandas
 Matplotlib
 Scipy
 Seaborn
 Sklearn

In [1]:
!pip install numpy
!pip install pandas
!pip install matplotlib
!pip install scipy
!pip install seaborn
!pip install sklearn

  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1320 sha256=6b5598f9028c06a914f24670494048f0b822aa223dfd611f7a6f7f6c674499b2
  Stored in directory: c:\users\pg007\appdata\local\pip\cache\wheels\22\0b\40\fd3f795caaa1fb4c6cb738bc1f56100be1e57da95849bfc897
Successfully built sklearn


# Working with Arrays, Vectors and Data frames

In [2]:
# Load library
import numpy as np

# Create a vector as a row
vector_row = np.array([1, 2, 3])

# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])

In [3]:
#print vector row
vector_row

array([1, 2, 3])

In [4]:
#print vector Column
vector_column

array([[1],
       [2],
       [3]])

In [5]:
#make a matrix or multi diamentional array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Applying Operations to all Vector elements

In [6]:

matrix = np.array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

# function to genetare multiple of 5

mul_5 = lambda x: x * 5
vectorized_mul_5 = np.vectorize(mul_5)

vectorized_mul_5(matrix)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

# Mean, Variance and Standard Deviation

In [8]:
np.mean(matrix)

5.0

In [9]:
np.var(matrix)

6.666666666666667

In [21]:
np.std(matrix)

2.581988897471611

# Transposing a Matrix

In [11]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Flattening a Matrix

In [12]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Dot Products of Vectors

In [13]:
a = np.array([3, 5, 6])
b = np.array([23, 15, 1])

np.dot(a, b)

150

# Adding, Subtracting and Multiplying Matrices

In [14]:
np.add(matrix, matrix)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [15]:
np.subtract(matrix, matrix)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
np.dot(matrix, matrix)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [17]:
matrix * matrix

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

# Data Frames

In [10]:
import pandas as pd

In [11]:
 data = {     'name': ['Xavier', 'Ann', 'Jana', 'Yi', 'Robin', 'Amal', 'Nori'],
   'city': ['Mexico City', 'Toronto', 'Prague', 'Shanghai',
             'Manchester', 'Cairo', 'Osaka'],
    'age': [41, 28, 33, 34, 38, 31, 37],
    'py-score': [88.0, 79.0, 81.0, 80.0, 68.0, 61.0, 84.0]
}

row_labels = [101, 102, 103, 104, 105, 106, 107]

In [12]:
df = pd.DataFrame(data=data, index=row_labels)

In [28]:
df

name         city  age  py-score
101  Xavier  Mexico City   41      88.0
102     Ann      Toronto   28      79.0
103    Jana       Prague   33      81.0
104      Yi     Shanghai   34      80.0
105   Robin   Manchester   38      68.0
106    Amal        Cairo   31      61.0
107    Nori        Osaka   37      84.0

In [29]:
df.head()

name         city  age  py-score
101  Xavier  Mexico City   41      88.0
102     Ann      Toronto   28      79.0
103    Jana       Prague   33      81.0
104      Yi     Shanghai   34      80.0
105   Robin   Manchester   38      68.0

In [31]:
df.tail()

name        city  age  py-score
103   Jana      Prague   33      81.0
104     Yi    Shanghai   34      80.0
105  Robin  Manchester   38      68.0
106   Amal       Cairo   31      61.0
107   Nori       Osaka   37      84.0

In [32]:
cities = df['city']
cities

101    Mexico City
102        Toronto
103         Prague
104       Shanghai
105     Manchester
106          Cairo
107          Osaka
Name: city, dtype: object

In [33]:
df.city

101    Mexico City
102        Toronto
103         Prague
104       Shanghai
105     Manchester
106          Cairo
107          Osaka
Name: city, dtype: object

In [34]:
cities[102]

'Toronto'

In [35]:
df.loc[103]

name          Jana
city        Prague
age             33
py-score        81
Name: 103, dtype: object